name: Hook Main and Tag

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  upload:
    name: Upload Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name:  install modules
        run: |
          npm ci --ignore-scripts
      - name:  push tag and deploy
        run: |
          npm run deploy
