name: Push release tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

env:
  NODE_VERSION: 18

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Push tag and deploy
        run: |
          npm ci
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          npm run deploy
