on:
  push:
    tags:
      - "akashic-engine@*"

name: Release and Upload Assets

env:
  NODE_VERSION: 18

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false # トリガーがpush:tags:の場合、キャッシュポイズニング攻撃のリスクがあるため、npm等のパッケージマネージャーのキャッシュを明示的に無効化する
      - name: Install project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Bundle project
        run: zip -r bundle.zip dist/
      - name: Create Release and Upload Assets
        run: |
          gh release create ${CURRENT_TAG} \
            --title "Release ${CURRENT_TAG}" \
            --generate-notes \
            ./bundle.zip \
            dist/akashic-engine-standalone-*.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TAG: ${{ github.ref }}
